var pointData=[
    {
        "area":"澎湖縣",
        "detail":"陽光、沙灘、海浪、仙人掌，還有一位老船長",
        "pict":"./pict/viewpoint/2.jpg"
    },{
        "area":"嘉義市",
        "detail":"好像只有噴水雞肉飯好吃?",
        "pict":"./pict/viewpoint/3.jpg"
    },{
        "area":"嘉義縣",
        "detail":"阿里山的姑娘美如水呀 阿里山的少年壯如山",
        "pict":"./pict/viewpoint/4.jpg"        
    },{
        "area":"臺中市",
        "detail":"好美、好吃、好拍、好逛，唯一缺點大概就是人比車兇?",
        "pict":"./pict/viewpoint/5.jpg"
    },{
        "area":"基隆市",
        "detail":"無時無刻都在下雨，名副其實的雨都",
        "pict":"./pict/viewpoint/6.jpg"
    },{
        "area":"屏東縣",
        "detail":"好像只有去過墾丁而已....",
        "pict":"./pict/viewpoint/7.jpg"
    },{
        "area":"臺北市",
        "detail":"最熱鬧、東西最貴的天龍人之都",
        "pict":"./pict/viewpoint/1.jpg"
        
    },{
        "area":"新北市",
        "detail":"人口最多的地方，面積最大但好像都差不多去過",
        "pict":"./pict/viewpoint/8.jpg"
    },{
        "area":"宜蘭縣",
        "detail":"很多好玩的地方，但國五每次一定塞爛",
        "pict":"./pict/viewpoint/8.jpg"
    },{
        "area":"桃園市",
        "detail":"市區不好玩，郊區好多點還沒踩:豬鼻子沙灘",
        "pict":"./pict/viewpoint/10.jpg"
    },{
        "area":"新竹市",
        "detail":"廟口鴨香飯真的讚，景點圍繞著城隍廟",
        "pict":"./pict/viewpoint/11.jpg"
    },{
        "area":"新竹縣",
        "detail":"六福村、香山步道...最多客家人的都市，客家之都",
        "pict":"./pict/viewpoint/12.jpg"
    },{
        "area":"苗栗縣",
        "detail":"入境檢疫14天的苗栗國，意外有不少景點",
        "pict":"./pict/viewpoint/13.jpg"
    },{
        "area":"彰化縣",
        "detail":"台商聚集地，還真的不知道有甚麼",
        "pict":"./pict/viewpoint/14.jpg"
    },{
        "area":"雲林縣",
        "detail":"我站在雲林....探索中",
        "pict":"./pict/viewpoint/15.jpg"
    },{
        "area":"花蓮縣",
        "detail":"風景很好，放鬆的好去處，只是遠到一個不行",
        "pict":"./pict/viewpoint/16.jpg"
    },{
        "area":"南投縣",
        "detail":"4面環山，不過很多景點蠻好玩的",
        "pict":"./pict/viewpoint/17.jpg"
    },{
        "area":"臺東縣",
        "detail":"真的好山、好水、好遠",        
        "pict":"./pict/viewpoint/18.jpg"
    },{
        "area":"臺南市",
        "detail":"美食之都，好玩又好吃",        
        "pict":"./pict/viewpoint/19.jpg"
    },{
        "area":"高雄市",
        "detail":"高雄發大財，超級不熟，每次都只到台南",        
        "pict":"./pict/viewpoint/20.jpg"
    },
];